### ISSUE TITLE
migration doesn't work for me neither

### ISSUE THREAD

**Issue by climb65** [bitmazk/django-booking#7]
Hello,

the migration process does not work.
I'm using Python 2.7 and django 1.10.

Error is:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 341, in execute
    django.setup()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/**init**.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/booking/models.py", line 14, in <module>
    class BookingStatus(TranslationModelMixin, TranslatableModel):
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 309, in **new**
    new_class._prepare()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 359, in _prepare
    signals.class_prepared.send(sender=cls)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/hvad/models.py", line 477, in prepare_translatable_model
    model.add_to_class('_base_manager', Manager())
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute

Here is the "pip list":

certifi (2016.8.8)
cffi (1.7.0)
cryptography (1.4)
Django (1.10)
django-booking (0.7.2)
django-countries (3.4.1)
django-hvad (1.5.1)
django-libs (1.67.5)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.16)
ndg-httpsclient (0.4.2)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (16.0.0)
setuptools (18.2)
six (1.10.0)
urllib3 (1.16)
wheel (0.24.0)

Thanks for your help.

**Comment by Tyrdall** [comment]
@climb65 Looks like a `django-hvad`issue. Are you sure hvad works with Django 1.10.?

**Comment by climb65** [comment]
Thanks for your quick reply.
Here is a related issue that might help django-booking users:

https://github.com/KristianOellegaard/django-hvad/issues/308

So the best way I think is to downgrade to django 1.9 for the moment.

**Comment by spectras** [comment]
Django 1.10.1 and hvad 1.6.0 are out, everything should be back to normal on the hvad side.
